### ISSUE TITLE
it would be handy to import similie-widgets/timeline rather than fork it

### ISSUE THREAD

**Issue by smurp** [Semandra/Timescape#2]
It appears to be a fork of:
  https://github.com/simile-widgets/timeline/commit/6c546be5ae546fb3b405a607984707b2dee4ac14

In other words that was the version of `timeline` that `Timescape` was based on.  Knowing this is useful so we can identify our changes and possibly factor them out or create a pull request.

**Comment by wolfmaul** [comment]
Agreed. Done.
